Repository GoodTripProject/GoodTripServer, pull requests merged in 2024-06, with the labels that each got.

#30 [BREAKING] Make some methods transactional
  src/main/java/com/goodtrip/goodtripserver/database/repositories/FollowersRepository.java
Labels: bug, backend

#13 Add server tests
  src/main/java/com/goodtrip/goodtripserver/database/configs/DatabaseConfig.java
  src/main/java/com/goodtrip/goodtripserver/database/models/Note.java
  src/main/java/com/goodtrip/goodtripserver/database/repositories/CountryVisitRepository.java
  src/main/kotlin/com/goodtrip/goodtripserver/authentication/route/AuthenticationController.kt
  src/main/kotlin/com/goodtrip/goodtripserver/authentication/service/AuthenticationServiceImpl.kt
  src/main/kotlin/com/goodtrip/goodtripserver/communication/route/CommunicationController.kt
  src/main/kotlin/com/goodtrip/goodtripserver/places/route/PlacesController.kt
  src/main/kotlin/com/goodtrip/goodtripserver/places/service/PlacesServiceImpl.kt
  src/test/kotlin/com/goodtrip/goodtripserver/authentication/AuthenticationTest.kt
  src/test/kotlin/com/goodtrip/goodtripserver/communication/CommunicationTest.kt
  src/test/kotlin/com/goodtrip/goodtripserver/places/PlacesTest.kt
  src/test/kotlin/com/goodtrip/goodtripserver/trip/route/TripControllerTest.kt
  src/test/kotlin/com/goodtrip/goodtripserver/trip/service/TripServiceImplTest.kt
  src/test/kotlin/com/goodtrip/goodtripserver/trip/utils/Utils.kt
  src/test/kotlin/com/goodtrip/goodtripserver/user/UserTest.kt
Labels: backend, tests

#32 Fixed bug with null imageLink
  src/main/java/com/goodtrip/goodtripserver/database/models/User.java
  src/main/kotlin/com/goodtrip/goodtripserver/authentication/service/AuthenticationServiceImpl.kt
Labels: bug, backend

#33 [BREAKING] Fix bug about user in trips
  src/main/java/com/goodtrip/goodtripserver/database/repositories/TripBaseRepositoryImpl.java
Labels: bug, backend

#15 Added asynchronous interaction
  build.gradle.kts
  src/main/java/com/goodtrip/goodtripserver/database/models/CountryVisit.java
  src/main/java/com/goodtrip/goodtripserver/database/models/Trip.java
  src/main/java/com/goodtrip/goodtripserver/database/repositories/TripBaseRepositoryImpl.java
  src/main/kotlin/com/goodtrip/goodtripserver/authentication/config/JwtAuthenticationFilter.kt
  src/main/kotlin/com/goodtrip/goodtripserver/authentication/config/JwtService.kt
  src/main/kotlin/com/goodtrip/goodtripserver/authentication/route/AuthenticationController.kt
  src/main/kotlin/com/goodtrip/goodtripserver/authentication/service/AuthenticationService.kt
  src/main/kotlin/com/goodtrip/goodtripserver/authentication/service/AuthenticationServiceImpl.kt
  src/main/kotlin/com/goodtrip/goodtripserver/authentication/service/UserService.kt
  src/main/kotlin/com/goodtrip/goodtripserver/authentication/service/UserServiceImpl.kt
  src/main/kotlin/com/goodtrip/goodtripserver/communication/route/CommunicationController.kt
  src/main/kotlin/com/goodtrip/goodtripserver/communication/service/CommunicationService.kt
  src/main/kotlin/com/goodtrip/goodtripserver/communication/service/CommunicationServiceImpl.kt
  src/main/kotlin/com/goodtrip/goodtripserver/flights/route/FlightsController.kt
  src/main/kotlin/com/goodtrip/goodtripserver/flights/service/FlightsService.kt
  src/main/kotlin/com/goodtrip/goodtripserver/flights/service/FlightsServiceImpl.kt
  src/main/kotlin/com/goodtrip/goodtripserver/places/route/PlacesController.kt
  src/main/kotlin/com/goodtrip/goodtripserver/places/service/PlacesService.kt
  src/main/kotlin/com/goodtrip/goodtripserver/places/service/PlacesServiceImpl.kt
  src/main/kotlin/com/goodtrip/goodtripserver/trip/route/TripController.kt
  src/main/kotlin/com/goodtrip/goodtripserver/trip/service/TripService.kt
  src/main/kotlin/com/goodtrip/goodtripserver/trip/service/TripServiceImpl.kt
  src/main/kotlin/com/goodtrip/goodtripserver/user/route/UserController.kt
Labels: enhancement, backend
